# Generated by Django 4.0.3 on 2022-05-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Blood_group', models.CharField(max_length=10)),
                ('District', models.CharField(max_length=20)),
                ('Mobile_number', models.CharField(max_length=13)),
                ('Mail_id', models.EmailField(max_length=50)),
                ('Photo', models.FileField(upload_to='')),
                ('Health_issue', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Validation', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Request_donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
